In [2]:
import numpy as np

#### 1. 等差数列

In [3]:
np.linspace(0, 100, 10, endpoint=False)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.])

In [4]:
np.linspace(0, 100, 10, endpoint=True)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [5]:
np.arange(0, 100, step=10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 2. 等比数列

In [6]:
np.geomspace(1, 1000, num=4)

array([    1.,    10.,   100.,  1000.])

In [7]:
np.geomspace(1e-4, 1e4, 8, endpoint=False)

array([  1.00000000e-04,   1.00000000e-03,   1.00000000e-02,
         1.00000000e-01,   1.00000000e+00,   1.00000000e+01,
         1.00000000e+02,   1.00000000e+03])

In [8]:
np.geomspace(1e-4, 1e4, 9)

array([  1.00000000e-04,   1.00000000e-03,   1.00000000e-02,
         1.00000000e-01,   1.00000000e+00,   1.00000000e+01,
         1.00000000e+02,   1.00000000e+03,   1.00000000e+04])

#### 3. 一个数列中最小值的index

In [9]:
random_seq = np.random.randint(10, size=10)
random_seq

array([1, 4, 3, 1, 6, 4, 4, 0, 1, 8])

In [10]:
np.argmin(random_seq)

7

#### 4. 生成全是1的矩阵

In [11]:
np.ones([3, 4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### 5. 连接两个矩阵

In [12]:
np.c_[np.ones([2, 3]), np.zeros([2, 3])]

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.]])

In [13]:
np.r_[np.ones([2, 3]), np.zeros([2, 3])]

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

#### 6. 生成两个数组的笛卡尔积 

In [14]:
# n^2 elements in each dimension, great way to do Cartesian product 
xx1, xx2 = np.meshgrid(np.arange(1, 4, 1), np.arange(5, 8, 1))
grid = np.c_[xx1.ravel(), xx2.ravel()]
grid

array([[1, 5],
       [2, 5],
       [3, 5],
       [1, 6],
       [2, 6],
       [3, 6],
       [1, 7],
       [2, 7],
       [3, 7]])

#### 7. 生成布尔向量

In [15]:
sv = np.zeros(4, dtype=bool)
sv

array([False, False, False, False], dtype=bool)

In [16]:
alpha = np.array([0, 2, 3, 0])
alpha

array([0, 2, 3, 0])

In [17]:
alpha.astype(bool)  # convert 0 to False, non-zero to True

array([False,  True,  True, False], dtype=bool)

#### 8. 所有元素相等

In [20]:
np.full((4, ), 6)

array([6, 6, 6, 6])

#### 9. 单位矩阵

In [21]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])