In [1]:
import numpy as np
from numpy import linalg as LA
from sklearn import datasets

In [2]:
X1 = np.array(np.arange(9)).reshape(3, 3)
X1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
X1.shape

(3, 3)

In [4]:
X2 = np.array(np.arange(4, 13)).reshape(3, 3)
X2

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### 1. 对应元素相乘(Hadamard Product)

In [5]:
np.multiply(X1, X2)

array([[ 0,  5, 12],
       [21, 32, 45],
       [60, 77, 96]])

### 2. 矩阵乘法

In [6]:
np.dot(X1, X2)

array([[ 27,  30,  33],
       [ 90, 102, 114],
       [153, 174, 195]])

### 3. 向量的内积结果是一个标量：对应元素相乘再相加

In [7]:
x3 = np.array(np.arange(2, 6))
x4 = np.array(np.arange(4, 8))
x3, x4

(array([2, 3, 4, 5]), array([4, 5, 6, 7]))

In [8]:
x3.shape

(4,)

In [9]:
np.inner(x3, x4)

82

### 4. 最大元素的index

In [10]:
X1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

**flatten vs ravel **
- https://stackoverflow.com/a/28930580/2803344

In [11]:
X1.flatten()  # always returns a copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
X1.ravel()  # returns a view of the original array whenever possible

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.argmax(X1)  # 在flatted arrary中的索引

8

In [14]:
np.argmax(X1, axis=0)  # 每列最大值的索引

array([2, 2, 2])

In [15]:
inx = np.unravel_index(np.argmax(X1, axis=None), X1.shape)

In [16]:
X1[inx]

8

### 5. 计算矩阵的特征向量，特征值
- https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.eig.html
- http://note.youdao.com/noteshare?id=0d219d6e70e0d93922f1c343a71a3022&sub=163D3B89B52441C88BB83472B4EA72B1

In [17]:
A = np.array([[5, -3, 0], [-3, 5, 0], [0, 0, 4]])
A

array([[ 5, -3,  0],
       [-3,  5,  0],
       [ 0,  0,  4]])

In [18]:
eigen_val, eigen_vec = LA.eig(A)

In [19]:
eigen_val

array([ 8.,  2.,  4.])

In [20]:
eigen_vec

array([[ 0.70710678,  0.70710678,  0.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

### 6. 上三角矩阵

In [21]:
iu1 = np.triu_indices(4,1)
iu1

(array([0, 0, 0, 1, 1, 2]), array([1, 2, 3, 2, 3, 3]))

In [22]:
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
a[iu1]

array([ 1,  2,  3,  6,  7, 11])

In [24]:
a[iu1] = -1
a

array([[ 0, -1, -1, -1],
       [ 4,  5, -1, -1],
       [ 8,  9, 10, -1],
       [12, 13, 14, 15]])

### 7. 计算协方差矩阵
- np.cov(x, rowvar=True, bias=False)
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html
- rowvar : bool, optional

If rowvar is True (default), then each row represents a variable, with observations in the columns. Otherwise, the relationship is transposed: each column represents a variable, while the rows contain observations.

- bias : bool, optional

Default normalization (False) is by (N - 1), where N is the number of observations given (unbiased estimate). If bias is True, then normalization is by N. These values can be overridden by using the keyword ddof in numpy versions >= 1.5.

In [25]:
x = np.array([[0, 2], [1, 1], [2, 0]]).T;x

array([[0, 1, 2],
       [2, 1, 0]])

In [26]:
np.cov(x)  # 两行，两个特征

array([[ 1., -1.],
       [-1.,  1.]])

In [27]:
np.cov(x, rowvar=False, bias=True)  # 三列，三个特征

array([[ 1.,  0., -1.],
       [ 0.,  0.,  0.],
       [-1.,  0.,  1.]])

### 8. 数列中真值的计数

In [28]:
sum([True,True,True,False,False])

3

In [29]:
a = np.arange(10)
np.sum(a==5)

1

### 9. array中元素的计数

In [30]:
iris = datasets.load_iris()
print('total raw data:', iris.data.shape, iris.target.shape)

total raw data: (150, 4) (150,)


In [31]:
iris.target[:5]

array([0, 0, 0, 0, 0])

In [32]:
np.unique(iris.target, return_counts=True)

(array([0, 1, 2]), array([50, 50, 50]))