In [1]:
import numpy as np

#### 1. 随机抽样
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html

In [2]:
a_list = list(range(5))
a_list

[0, 1, 2, 3, 4]

##### 1.1 有放回抽样

In [3]:
sample1 = np.random.choice(a_list, 3)
sample1

array([4, 3, 2])

In [4]:
sample2 = np.random.choice(a_list, 10)
sample2

array([1, 4, 0, 1, 3, 2, 1, 1, 3, 1])

##### 1.2 定义每个元素的概率

In [5]:
sample3 = np.random.choice(a_list, 10, p=[0, 0.2, 0.5, 0.1, 0.2])
sample3

array([1, 1, 3, 4, 2, 4, 2, 2, 4, 2])

##### 1.3 不放回抽样

In [8]:
sample4 = np.random.choice(a_list, 4, replace=False)
sample4

array([0, 4, 3, 1])