In [5]:
import numpy as np

#### 1. 等差数列

In [28]:
np.linspace(0, 100, 10, endpoint=False)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.])

In [29]:
np.linspace(0, 100, 10, endpoint=True)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [26]:
np.arange(0, 100, step=10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 2. 等比数列

In [18]:
np.geomspace(1, 1000, num=4)

array([    1.,    10.,   100.,  1000.])

In [31]:
np.geomspace(1e-4, 1e4, 8, endpoint=False)

array([  1.00000000e-04,   1.00000000e-03,   1.00000000e-02,
         1.00000000e-01,   1.00000000e+00,   1.00000000e+01,
         1.00000000e+02,   1.00000000e+03])

#### 3. 一个数列中最小值的index

In [40]:
random_seq = np.random.randint(10, size=10)
random_seq

array([9, 9, 4, 2, 6, 8, 2, 1, 2, 7])

In [41]:
np.argmin(random_seq)

7