In [1]:
import numpy as np

#### 1. 等差数列

In [2]:
np.linspace(0, 100, 10, endpoint=False)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.])

In [3]:
np.linspace(0, 100, 10, endpoint=True)

array([   0.        ,   11.11111111,   22.22222222,   33.33333333,
         44.44444444,   55.55555556,   66.66666667,   77.77777778,
         88.88888889,  100.        ])

In [4]:
np.arange(0, 100, step=10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

#### 2. 等比数列

In [5]:
np.geomspace(1, 1000, num=4)

array([    1.,    10.,   100.,  1000.])

In [6]:
np.geomspace(1e-4, 1e4, 8, endpoint=False)

array([  1.00000000e-04,   1.00000000e-03,   1.00000000e-02,
         1.00000000e-01,   1.00000000e+00,   1.00000000e+01,
         1.00000000e+02,   1.00000000e+03])

#### 3. 一个数列中最小值的index

In [7]:
random_seq = np.random.randint(10, size=10)
random_seq

array([0, 5, 7, 6, 5, 5, 6, 5, 6, 0])

In [8]:
np.argmin(random_seq)

0

#### 4. 生成全是1的矩阵

In [11]:
np.ones([3, 4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

#### 5. 连接两个矩阵

In [12]:
np.c_[np.ones([2, 3]), np.zeros([2, 3])]

array([[ 1.,  1.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.,  0.]])

In [13]:
np.r_[np.ones([2, 3]), np.zeros([2, 3])]

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])