## 1. 数组(array)
R中的数组使用array进行创建，与向量不同的是，array可以是多维的（可简单理解为拥有dimension的vector(可以是1,2,...,n个维度)）。array中的数据同样是相同类型的。

array函数的形式为：
array(vector, dimensions, dimnames)，其中vector包含array中的元素，dimensions是一个向量指定array各个维度的大小，dimnames是一个list指定各个维度对应的名称。

<img src="./images/matrix.png" />

<img src="./images/array.png" />

矩阵和数组的结构，图片来源：https://www.neonscience.org/hsi-hdf5-r

### 1.1 创建数组及取值

In [1]:
a <- c(1,3,4,5,6,7,8,9,3)
cat(a)

1 3 4 5 6 7 8 9 3

#### 1.1.1 通过定义dim(维度)将向量变成数组

In [2]:
dim(a) <- c(3, 3)  # 2维数组，同矩阵

In [3]:
a

[,1] [,2] [,3]
[1,] 1    5    8   
[2,] 3    6    9   
[3,] 4    7    3

In [4]:
is.array(a)

[1] TRUE

In [5]:
is.matrix(a)

[1] TRUE

#### 1.1.2 使用array函数定义数组

In [6]:
v <- 1:9
cat(v)

1 2 3 4 5 6 7 8 9

In [7]:
B <- array(data = v, dim = c(3, 3))  # 默认按列创建数组
B

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [8]:
v2 <- 1:18
cat(v2)

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18

创建一个3维数组

In [9]:
C <- array(data = v2, dim = c(3, 3, 2), dimnames = list(c('a', 'b', 'c'),
                                                        c('d', 'e', 'f'),
                                                        c('g', 'h')))

In [10]:
C[,,1]  # 用整数index取值

d e f
a 1 4 7
b 2 5 8
c 3 6 9

In [11]:
C[,,2]  # 

d  e  f 
a 10 13 16
b 11 14 17
c 12 15 18

In [12]:
C['c','d','g']  # 用维度的名称取值

[1] 3

In [13]:
is.matrix(C)

[1] FALSE

In [14]:
is.array(C)

[1] TRUE

### 1.2 数组的属性

#### 1.2.1 维度信息

In [15]:
dim(C)

[1] 3 3 2

#### 1.2.2 元素的个数

In [16]:
length(C)

[1] 18

### 1.2.3 元素类型

In [17]:
mode(C)

[1] "numeric"

## 2. 矩阵

R语言中的矩阵matrix是一个二维的数组array，因此数组array的一些操作矩阵适用。除此之外，矩阵还具有一些数组没有，矩阵特有的运算。

**matrix函数的形式为**：

matrix(vector, nrow=number_of_rows, ncol=number_of_columns, byrow=logical_value, dimnames=list(rownames, colnames))，该函数中，vector中为矩阵的元素，nrow表示行数，ncol表示列数，byrow为一个布尔向量表示是否按照行为主进行填充，默认按照列为主，dimnames为可选的制定行和列的名称。

### 2.1 创建一个矩阵

除了用上面的`array`函数，修改`dim`信息来创建矩阵之外，还可以使用`matrix`来创建矩阵

这些方法无一例外都是对向量的变形

In [18]:
M1 <- matrix(1:8, nrow = 2, ncol = 4)  # 默认按列创建矩阵
M1

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [19]:
M2 <- matrix(1:8, nrow = 2, ncol = 4, byrow = T)  # 按行创建矩阵
M2

[,1] [,2] [,3] [,4]
[1,] 1    2    3    4   
[2,] 5    6    7    8

### 2.2 矩阵的属性

#### 2.2.1 矩阵的维度信息

In [20]:
dim(M1)

[1] 2 4

#### 2.2.2 矩阵的行名和列名

In [21]:
rownames(M1) <- c('r1', 'r2')
colnames(M1) <- c('a', 'b', 'c', 'd')
M1

a b c d
r1 1 3 5 7
r2 2 4 6 8

In [22]:
cat(colnames(M1))

a b c d

### 2.3 apply函数

apply(X, MARGIN, FUN)函数可以将函数`FUN`应用到矩阵`X`的行或列

参数`MARGIN=1`表示按行进行计算，`MARGIN=2`表示按列进行计算

In [23]:
apply(X = M1, MARGIN = 1, FUN = sum)

r1 r2 
16 20

In [24]:
apply(X = M2, MARGIN = 2, FUN = mean)

[1] 3 4 5 6

### 2.4 两个矩阵的连接

In [25]:
M1

a b c d
r1 1 3 5 7
r2 2 4 6 8

In [26]:
rownames(M2) <- c('r3', 'r4')
colnames(M2) <- letters[c(2, 1, 3, 4)]  # `letters`表示a-z字母列表
M2

b a c d
r3 1 2 3 4
r4 5 6 7 8

In [27]:
rbind(M1, M2)  # 按照扩展行的方式连接矩阵，不会参考列名对列进行重排序

a b c d
r1 1 3 5 7
r2 2 4 6 8
r3 1 2 3 4
r4 5 6 7 8

In [28]:
cbind(A=1:4, B=5:8, C=9:12)  # 按照扩展列的方式连接矩阵

A B C 
[1,] 1 5  9
[2,] 2 6 10
[3,] 3 7 11
[4,] 4 8 12

### 2.5 与矩阵相关的其他操作

转置：t(A)

求行列式：det(A)

矩阵相乘：x%*%y

对角运算：diag(A)

求逆：solve(A,b)

求特征值和特征向量：eigen(A)

奇异值分解：svd(A)

In [29]:
t(M1)  # 转置

r1 r2
a 1  2 
b 3  4 
c 5  6 
d 7  8