### 特征的缩放(Feature Scaling)
- 由于SVM对特征的尺度比较敏感，因此使用之前最好将所有特征的尺度标准化到同一个尺度上
- 缩放是在每个特征内部进行的
- 可以使用sk-learn中的StandardScaler或者MinMaxScaler
- Hands-On Machine Learning, p65
- http://scikit-learn.org/stable/auto_examples/preprocessing/plot_scaling_importance.html
- very good introduction, http://benalexkeen.com/feature-scaling-with-scikit-learn/

#### 1. StandardScaler
- http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
- 对矩阵按列进行标准化
- 先减去均值，再除以标准差
- Standardization of a dataset is a common requirement for many machine learning estimators: they might behave badly if the individual feature do not more or less look like standard normally distributed data (e.g. Gaussian with 0 mean and unit variance).

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
X = np.arange(12).reshape(3, 4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
scaler = StandardScaler()
scaler.fit(X)
print(scaler)
print(scaler.mean_, scaler.scale_)

StandardScaler(copy=True, with_mean=True, with_std=True)
[ 4.  5.  6.  7.] [ 3.26598632  3.26598632  3.26598632  3.26598632]


D:\tools\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [4]:
np.std(X[:, 0])  # scaler.scale_ 同每一列的标准差

3.2659863237109041

In [5]:
X_scaled = scaler.transform(X)
X_scaled

D:\tools\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

In [6]:
(X - scaler.mean_) / scaler.scale_  # 减去均值，再除以标准差

array([[-1.22474487, -1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487,  1.22474487]])

#### 2. MinMaxScaler
- http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html
- 标准化到[0, 1]，或者到一个范围[min, max]
- 计算过程如下

```
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min
```

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
scaler2 = MinMaxScaler()
scaler2.fit(X)
print(scaler2)

MinMaxScaler(copy=True, feature_range=(0, 1))


D:\tools\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [10]:
X_scaled2 = scaler2.transform(X)
X_scaled2

array([[ 0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ]])